version: '3.9'

services:
  yggdrasil:
    image: yggdrasil:latest
    build:
      context: .
    container_name: yggdrasil
    environment:
      - YGGDRASIL_VERSION=0.0.0
    ports:
      - "8899:8080"
      - "8900:8088"
    restart: always
