version: '3.9'

services:
  yggdrasil:
    image: yggdrasil:latest
    build:
      context: .
      args:
        - YGGDRASIL_VERSION=${YGGDRASIL_VERSION}
    container_name: yggdrasil
    environment:
      - YGGDRASIL_VERSION=${YGGDRASIL_VERSION}
    ports:
      - "8899:8080"
    restart: always
