name: Run Tests in Container

on:
    push:
      branches-ignore:
        - main
      paths-ignore:
        - CHANGELOG.md
        - CONTRIBUTING.md
        - LICENSE
        - renovate.json
        - docker-compose.yml
        - Dockerfile
    workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: eclipse-temurin:21
      env:
        YGGDRASIL_VERSION: ${{ vars.GITHUB_REF_NAME }}
        TERM: dumb
      ports:
        - "8899:8080"
        - "8900:8088"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run checks and tests
        run: ./gradlew check
      - name: Upload analysis to GitHub
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: check-results
          path: |
            cartago/build/reports
            http/build/reports
            messages/build/reports
            store/build/reports
            utils/build/reports
            websub/build/reports
            build/reports
          if-no-files-found: error
      - name: Upload app to GitHub
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: app
          path: build/libs/yggdrasil-${YGGDRASIL_VERSION}-SNAPSHOT-all.jar
          if-no-files-found: error
      - name: Upload conf to GitHub
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: conf
          path: conf/docker_disk_config.json
          if-no-files-found: error

  build-container:
    needs: build-app
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: eclipse-temurin:21
      env:
        YGGDRASIL_VERSION: ${{ vars.GITHUB_REF_NAME }}
      ports:
        - "8899:8080"
        - "8900:8088"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        uses: actions/download-artifact@master
        with:
          name: app
          path: /opt/app/yggdrasil-${YGGDRASIL_VERSION}-SNAPSHOT-all.jar
      -
        uses: actions/download-artifact@master
        with:
          name: conf
          path: /opt/conf/docker_disk_config.json
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: galess/ics-hsg-yggdrasil:${{ vars.GITHUB_REF_NAME }}